### ISSUE TITLE
swagger-ui.html?

### ISSUE THREAD

**Issue by ayyagari** [pgilad/spring-boot-webflux-swagger-starter#1]
**swagger-ui.html missing?**
Following this code I could get `http://localhost:8080/v2/api-docs` showing me the JSON details of the API endpoints. However to get `http://localhost:8080/swagger-ui.html` displayed like the way it is shown in README.MD's Usage section, you need to add steps to get that Swagger UI up and running.

**Comment by pgilad** [comment]
That's kind of odd, I just tried to `git clone` and `gradle bootRun` and opened `http://localhost:8080/swagger-ui.html` and it worked like a charm. Can you specify what OS, Java and Gradle version you are running?
